services:
  ollama-server:
    container_name: ollama-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OLLAMA_MODEL: ${OLLAMA_MODEL:-qwen2.5:0.5b}
    networks:
      ollama-network:
        aliases:
          - ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama-model-cache:/root/.ollama/models
    restart: unless-stopped

volumes:
  ollama-model-cache:

networks:
  ollama-network:
    driver: bridge
